# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a35e799e5bfb1f50f6729bdcb828a2987994880d62b9c59fc8ba83ea84d30a8de2406ab6d012d9da83ab58aaf5e53a1c6429e3bd42d4b22bbe33cecba70945f

test:
  secret_key_base: 13415b79f5155d7e64497497550986cd5039cba7846ad62a4054c88e4ff698ca1b1d0883158a20de9f83a5c2b3f1ce9d1646db58987104f2607643ea73f87d62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
